version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello_dev
    ports:
      - "32768:5432"
  adminer:
    image: adminer
    restart: always
    ports:
        - 5428:8080
  web:
    build: .
    image: helloapp
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - PG_HOST=postgres
      - PG_PASSWORD=postgres
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - db
    command: mix ecto.create && mix phx.server
    depends_on:
      - db
